on:
  push:
    branches:
      - main

jobs:
  backoffice_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=babs105/backofficev2:latest
          cache-to: type=inline
          tags: babs105/backofficev2:latest
          build-args: PROFILE=nectar,ARG2=test
#name: deploy
#on:
#  push:
#    branches:
#      - main
#      - master
#
#jobs:
#  run-unit-tests:
#    runs-on: self-hosted
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#
#      - name: Setup Maven
#        uses: stCarolas/setup-maven@v4.4
#        with:
#          maven-version: 3.8.2
#
#      - name: Unit Tests
#        run: mvn clean package
#
#      - name: Rename the artifact
#        run: cp target/backofficev2-0.0.1-SNAPSHOT.jar backofficev2-${{ github.sha }}.jar
#
#      - name: Save the artifact
#        uses: actions/upload-artifact@master
#        with:
#          name: backofficev2
#          path: backofficev2-${{ github.sha }}.jar
#
#  fake-deploy:
#    runs-on: self-hosted
#    needs: run-unit-tests
#    steps:
#      - name: Get the artifact
#        uses: actions/download-artifact@master
#        with:
#          name: backofficev2
#
#      - name: Fake deploy
#        run: ls backofficev2-*.jar
